src/assets/netteForms.js

I get `Uncaught TypeError: Cannot read property 'tagName' of undefined` when I have input without name in the form.
I've made hotfix for that. But sorry, currently without tests.
I can write them in next few days if necessary.

netteForms.js: Fixed "Uncaught TypeError: Cannot read property 'tagName' of undefined"

---

src/assets/netteForms.js

When I create form and not all of inputs are rendered, JavaScript fails with errors.
So I've added these simple conditions that check if DOM Node exists or not.
Maybe, it should write `console.error` or something like this instead of silent ignore.

netteForms.js: Fixed errors for rules on non-present elements

---

src/Forms/Form.php
tests/Forms/Forms.onSuccess.phpt

Fixed onError event dispatching

---

src/Forms/Rendering/DefaultFormRenderer.php

nette/utils#111 has renamed `Html::add()` to `Html::addHtml()`, this is a followup pull request to use the new name in nette/forms

Rename Html:add() to Html:addHtml() to follow nette/utils#111

---

src/assets/netteForms.js

It triggers error `'focus' má hodnotu null nebo není objekt.` in IE8 because `in` iterates over all properties, even `indexOf` etc.

Fixed Nette.showFormErrors()

---

src/assets/netteForms.js

When there is different error message for min/max, then checking min or max via `range()` can cause it fails during `min` validation for `max` invalidity (and vice versa) - due to `rangeUnderflow`/`rangeOverflow`. Then wrong error message may be shown.

Cannot use range() to validate min/max

---

src/Forms/Controls/BaseControl.php
tests/Forms/Controls.Checkbox.render.phpt
tests/Forms/Controls.CheckboxList.render.phpt
tests/Forms/Controls.MultiSelectBox.render.phpt
tests/Forms/Controls.RadioList.render.phpt
tests/Forms/Controls.SelectBox.render.phpt
tests/Forms/Controls.TextArea.render.phpt
tests/Forms/Controls.TextInput.render.phpt
tests/Forms/Controls.UploadControl.render.phpt

This is just idea.
Error messages are since 6451fe0412012c7dac6ad507457d525b67a60bf6 translated by form's translator instead of control's one. It turned out to be the right decision. What about labels? I think that labels should be translated by form's translator too.
Maybe selectbox prompt too, but I am not sure.

BaseControl, SelectBox: labels and prompt are translated by global translator

---

src/Bridges/FormsLatte/FormMacros.php
tests/Forms.Latte/FormMacros.forms.phpt
tests/Forms.Latte/expected/FormMacros.forms.html
tests/Forms.Latte/expected/FormMacros.forms.phtml
tests/Forms.Latte/templates/forms.latte

- bug fix? yes
- new feature? no
- BC break? no
Currently `n:class` and `n:name` macros do not play well together. The problem is that `n:name` macro doesn't see `n:class` as html attribute, so it doesn't reset the class on the returned Html instance of form/label/control. This leads to HTML output with double `class="..."` attribute.
This PR solves the problem by adding explicit support for `n:class` into `FormMacros`.

Fix compatibility between n:class macro and n:name form macro.

---

src/Forms/Validator.php
tests/Forms/Controls.TestBase.validators.phpt

- bug fix? yes  [issue](/nette/http/issues/130)
- new feature? no
- BC break? no
- doc PR: nette/docs#???  not necessary
Validator accept pattern for FileUpload::getName() instance of FileUplaod::__toString(), where is tmpName.
```
$form->addUpload('csv')
->addRule($form::MIME_TYPE, 'Foo', 'text/*')
->addRule($form::PATTERN, 'Message', '.*\.csv');
```

Validator: method validatePattern() check FileUpload and use right name

---

src/Forms/Rules.php
tests/Forms/Rules.reset.phpt

- new feature: yes
- BC break? yno
- doc PR: not yet
Ability to reset already attached rules on control. It's not possible to attach different rules in modular systems. Or is it?
```php
$form = new Form;
$input = $form->addText('text');
$input->addCondition(Form::MAX_LENGTH, 5)
->addRule(Form::PATTERN, 'Musí obsahovat číslici', '.*[0-9].*');
$input->getRules()->reset();
```
Reset method is marked as internal.

Rules: added reset method

---

src/Forms/Rendering/DefaultFormRenderer.php
tests/Forms/Forms.renderer.4.phpt

- bug fix #181 
- BC break? no
- doc PR: not need
Item name is generated from parameter, where remove from first left bracket to end. For example list[foo][0] -> list.

DefaultFormRenderer: fix input name defined like array

---

src/assets/netteForms.js

- bug fix / new feature? a little bit of both
- BC break? no
- doc PR: not necessary I believe
This is a complement to #175 so validating file names via pattern works on both client and server.
I'm not sure how backporting to `v2.4` works - do you do that manually? Anything I need to do?
Not sure how to write tests for this - to _select_ a file in the test environment to test this. Appreciate any pointers.
Thank you.

netteForms.js: support checking file name via pattern rule

---

src/Forms/Form.php
src/Forms/Validator.php
src/assets/netteForms.js
tests/Forms/Controls.TestBase.validators.phpt
tests/netteForms/spec/Nette.validateRuleSpec.js

- bug fix / new feature? a little bit of both; fixes #185
- BC break? no
- doc PR: TBD
This adds an option to validate form controls like via `Form::PATTERN`, but with case-insensitive regexp. 
1. Not sure about the name. 
2. Hesitated between an internal common validation method and two _child_ methods - case-sensitive and case-insensitive, but went for this compact solution.
I have a question about the `u` regexp modifier. It is used in the PHP code, but not in the JS code. However, when I add it to the JS code, the tests break. Do you have more info on this? I thought this would result in enabled case folding on both sides consistently, but ... I don't know, this is not my area of expertise.
Appreciate any pointers / ideas for improvements.
Thank you.

add a case-insensitive variant of Form::PATTERN

---

src/Forms/Controls/BaseControl.php
src/Forms/Validator.php
tests/Forms/Controls.TestBase.validators.phpt
tests/Forms/Forms.idMask.phpt

- bug fix #190 
- BC break? no
- doc PR: no
The method validatePattern accepts $control where value can be array by UploadControl (multiple). If one file does not matched method return false.
I extend the test method because two classes MockUploadControl are not allowed.

Validator: method validatePattern() for UploadControl multiple

---

src/Forms/Controls/BaseControl.php
src/Forms/Controls/MultiSelectBox.php
src/Forms/Controls/SelectBox.php
tests/Forms/Forms.idMask.phpt

- bug fix / new feature?  none
- BC break? no
Added getters for optionAttributes - this makes inheriting these classes possible

optionAttributes getters

---

composer.json
examples/localization.php
src/Forms/Controls/BaseControl.php
tests/Forms/Controls.Button.render.phpt
tests/Forms/Controls.Checkbox.render.phpt
tests/Forms/Controls.CheckboxList.render.phpt
tests/Forms/Controls.HiddenField.render.phpt
tests/Forms/Controls.ImageButton.render.phpt
tests/Forms/Controls.MultiSelectBox.render.phpt
tests/Forms/Controls.RadioList.render.phpt
tests/Forms/Controls.SelectBox.render.phpt
tests/Forms/Controls.TextArea.render.phpt
tests/Forms/Controls.TextInput.render.phpt
tests/Forms/Controls.UploadControl.render.phpt
tests/Forms/Controls.translate().phpt
tests/Forms/Forms.renderer.translate.phpt

- BC break? yes
- Related to nette/utils#178

Allow multiple parameters for translated messages

---

examples/bootstrap4-rendering.php
src/Forms/Rendering/DefaultFormRenderer.php
tests/Forms/Forms.renderer.2.expect
tests/Forms/Forms.renderer.2.phpt

Bootstrap 4 [marks](https://getbootstrap.com/docs/4.2/components/forms/#how-it-works) invalid controls with `is-invalid` class. Let’s allow to set this class in `DefaultFormRenderer`.
- new feature
- BC break? no

DefaultFormRenderer: Add control .error class

---

src/assets/netteForms.js

- new feature
- BC break? no
this is useful eg. for controls manually rendered as table cells `<td>` which have only `<tr>` valid parent .. if there are multiple cells within table row toggling via `id` is not feasible (it would toggle all the cells in that row).

netteForms.js: support for toggling by css class, not only id

---

src/Forms/Validator.php
tests/Forms/Controls.TextInput.valueObjectValidation.phpt

- new feature
- BC break? no
- doc PR: not really needed
With introduction of scalar typehints it became impossible to use a couple of default validators with input controls that return value objects. This PR adds typecasts to URL and EMAIL validator to restore value object support.

Validator: add support for value objects

---

src/assets/netteForms.js

- bug fix https://github.com/nette/forms/issues/212
- BC break? no

netteForms: toggle back compatibility fix

---

src/Forms/Container.php
src/Forms/Controls/SubmitButton.php
src/Forms/Form.php

- new feature
- BC break? no
Hi,
are you interested in definition for callables like phpstan does?
format is like in php (without parameter names) `callable(params): return_type`
If you are interested I can change other classes/packages.

Use phpstan callable definitions

---

src/Forms/Rendering/DefaultFormRenderer.php
tests/Forms/Forms.renderer.6.phpt

- bug fix
- BC break? no
- doc PR:
After update on new version with strict_type=1, `DefaultFormRenderer` started throw `TypeError: preg_split() expects parameter 2 to be string, null given` for forms with method `GET` if action URL does not contain query string parameters.

bug fix DefaultFormRenderer

---

src/Forms/Rendering/DefaultFormRenderer.php
tests/Forms/Forms.objectAction.phpt

`Forms\Form` allows to pass stringable objects to `setAction` method, which is also used by `Application\UI\Form` to store `Application\UI\Link` object. `DefaultFormRenderer` calls string manipulation functions on the `Form’s` action when rendering, causing it to raise a `TypeError` when strict types are enabled.
To fix this, I am stringifying the action in the `DefaultFormRenderer`. I have opted to do it there, rather than in the `Form::setAction` method, in case the `Link` object is not ready yet at the time the `Form` is created.
Closes: https://github.com/nette/application/issues/218

DefaultFormRenderer: Fix GET Application\UI\Form

---

src/Forms/Form.php

- bug fix, related to #216 
- BC break? no
- doc PR: not needed
See [forum thread](https://forum.nette.org/cs/32188-staticka-analyza-kodu-po-aktualizaci-knihoven-na-nette-3-pri-lvl-5-hlasi-chyby#p204424). The import was missing, causing static analysis to report false positives.

Revert callable type of Form::$onSuccess to accept mixed

---

src/Forms/Controls/BaseControl.php

Labels with Nette\Utils\Html are not translated

---

src/Forms/Container.php

- bug fix / new feature? bug fix (no issue number)
- BC break? no
The second parameter for `onValidate` callback (`$values`) documented as `mixed` to follow the consensus for `onSuccess` (in #223)
Thanks!

Document the second param for onValidate callback

---

src/Forms/Validator.php
tests/Forms/Controls.TextInput.render.phpt

Fixes using label placeholder in validation rule with Html label

---

src/Forms/Validator.php
tests/Forms/Controls.BaseControl.phpt

- bug fix? yes
- BC break? no
The validator does not return the same label if the translator is null.

Validator::formatMessage() same label translations

---

examples/bootstrap2-rendering.php
examples/bootstrap3-rendering.php
examples/bootstrap4-rendering.php
examples/custom-control.php
src/Forms/Controls/HiddenField.php
tests/Forms/Controls.CsrfProtection.phpt
tests/Forms/Controls.HiddenField.loadData.phpt

- bug fix? no (issue #152)
- new feature? yes
- BC break? yes
Based on issue #152 `HiddenField` now supports `addFilter()`. Due to this new behavior is necessary support nullable also.
BC break: HiddenField now returns set value, no it's string version.

HiddenField support addFilter and nullable

---

src/Forms/Container.php

- BC break? no
If setDefaultValue can receive any type then this should be supported in addHidden method as well.
Now it's strange that you cannot  do this:
`$this->addHidden('count', 0);`
but you can do:
`$this->addHidden('count')->setDefaultValue(5);`

Container::addHidden Allow any type so it works same as setDefaultValue

---

src/Forms/Validator.php

- bug fix  
- BC break? no
If $caption is null, php throws rtrim() expects parameter 1 to be string, null given

strict types

---

src/Forms/Container.php

- bug fix
- BC break? no
It breaked unit tests on  project, not sure if it's only unit tests or also code related as well, but whenever I have container which name was numeric I'm getting exception:
```
TypeError : ReflectionClass::hasProperty() expects parameter 1 to be string, int given
/var/www/vendor/nette/forms/src/Forms/Container.php:124
```

strict fix

---

src/Forms/Validator.php

- new feature
- BC break? no
In case of:
```php
$form->addText('stars', 'Stars')
->setRequired('Please select stars.')
->addRule(Form::NUMERIC)
->addRule(Form::MIN, null, 0)
->addRule(Form::MAX, null, 5);
```
It is not clear from the original message in which validation rule the validation message is missing. The form can be built dynamically from multiple places. This feature adds the name of the validation rule that requires the message.
Thank you.

Missing validator message should contain validator name.

---

src/Forms/Controls/BaseControl.php

- type annotation change
- BC break? yes
It can only be set to a string, bool or null but when set to null, it will be auto-generated as string. This is technically a BC break since if someone returns a wider type in an overloaded method of a subclass, it will break covariance.
I am not actually sure what the `bool` type is for, most uses of `getHtmlId()` just treat it as if it were of type `string`: https://github.com/nette/forms/search?q=getHtmlId

BaseControl: narrow htmlId type

---

src/Forms/Rendering/DefaultFormRenderer.php

- Easier extensibility 
- BC break? no
Riesil som problem kde som potreboval upravit renderovanie checkboxu.
Nette `Checkbox::getControl` renderuje tuto struktutu
```
<div>
<label>
<checkbox />
</label>
</div
```
Ja som ale potreboval toto
```
<div>
<label />
<checkbox />
</div>
```
Toto sa da dosiahnut len ak si extendnem `\Nette\Forms\Rendering\DefaultFormRenderer` a vnom extendnem 
- `\Nette\Forms\Rendering\DefaultFormRenderer::renderControl`
- `\Nette\Forms\Rendering\DefaultFormRenderer::renderPairMulti`
- `\Nette\Forms\Rendering\DefaultFormRenderer::doRenderErrors`
Vo funkciach `renderControl` a `renderPairMulti` kde je riadok `$el = $control->getControl();` sa robi to kuzlo ktore potrebujem. Tento pull request jednoducho tuto cast kodu vytiahne do funkcie ktoru je jednoduche …

renderer - easier extensibility

---

src/Forms/Controls/DateTimeControl.php

- bug fix / new feature?   bugfix
- BC break? no
Use `self::TypeDate` as default for `DateTimeControl::$type`, not `self::Date`
This seems to be an unwanted change introduced in 3.2.1 in [01039d1](https://github.com/nette/forms/commit/01039d16add7973f06ac54ff3da37e85946d99e1#diff-db71c7b28f089ac2153db72b619314fa4b79ef034de79d6dab1120d47022b021R36).
Also reported by PHPStan here https://github.com/nette/forms/actions/runs/8458879610/job/23174056805#step:5:164

Use `self::TypeDate` as default for `DateTimeControl::$type`, not `self::Date`

---

src/Forms/Container.php

Containers are already supported, it just was not reflected in the type hint.
- bug fix
- BC break? no
- doc PR: no

Container::validate(): add Container to $controls param typehint

---

src/Forms/Form.php

In some cases we can use forms without even a submit button do validate some data, also sometimes in tests we do not add submit button because its maybe added elsewhere (onRender for example)...
Now  whenever this happens we get
Typed property Nette\Forms\Form::$submittedBy must not be accessed before initialization, this should solve it.

set SubmitterControl default to false

---

src/Forms/Container.php
src/Forms/Controls/BaseControl.php

Method Container::setDefaults() use different algorithm for filling default values into disabled controls than method BaseControl::setDefaultValue(), this commit unified both algorithms and fixes bug with dissappearing default value in submitted forms
- bug fix
- BC break - no
- doc -problem is described on nette forum: https://forum.nette.org/cs/36480-rfc-container-setdefaults-opravit-chybu-basecontrol-setdisabled-vylepsit-funkci
The bug consists in the fact that if we send the default data setDefaults() to the form element that is disabled by setDisabled() after the anchor event of the form, the data will disappear after the form is submitted, which is undesirable behavior. If we use the setDefaultValue() method, the data does not disappear and it is OK. This PR changes algorithm in …

Fix bug in method setDefaults() used on disabled form control

---

src/Forms/Controls/Button.php

If form is submitted with standard SubmitButton and in the form is another button Button, the attribute name + value appears in $values of the form. This is undesirable behaviour and my proposal fixes this bug.
- bug fix 
- BC break? no
- doc bug is described in detail on nette forume here https://forum.nette.org/cs/36506-osetrit-odesilana-data-tlacitka-nette-forms-controls-button#p226917
Notice: in the class Nette\Forms\Controls\SubmitButton in constructor is similar call setOmitted(true) which would be redundant after accepting this PR and could be removed for simplicity. I will send another PR.

Fix bug missing setting setOmitted(true) in Button.php

---

src/assets/formValidator.ts

- bug fix
- BC break? no
- doc PR: is it necessary?
As reported in https://forum.nette.org/cs/36618-duplicitni-dialog-netteformsmodal-s-ajaxem-naja-js, when somebody uses netteForms and Naja (>= 3.2) together, and netteForms are loaded (and auto-initialized) before Naja, both libraries consecutively trigger the form validation, which results in duplicate dialogs when there are validation errors.
This change prevents the `submit` event from propagating even to other listeners attached to the same form and event.

netteForms: do not propagate 'submit' event further when the form is invalid

---

src/Forms/Controls/SelectBox.php
tests/Forms/Controls.SelectBox.render.phpt

- bug fix 
- BC break? no
Example code:
```
$form->addSelect('country', 'Country', ['sk' => 'Slovakia', 'cz' => 'Czech Republic'])
->setRequired()	
->checkDefaultValue(false)
->setPrompt('-- select value --')
->setDefaultValue('en'); // value does not exists
```
The expected behavior is that the prompt will be selected but the first item is selected.
In version <= 3.2.1 this worked correctly.

Fix selectBox prompt + required + checkDefaultValue = False
